[project]
name = 'Tokenized-Small-Business-Financing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.investor-distribution]
path = 'contracts/investor-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.loan-management]
path = 'contracts/loan-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.revenue-certification]
path = 'contracts/revenue-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
